
# Playbook exacc_setup.yml creates an Exadata Cloud at Customer environment by calling the Exadata VM Cluster role,
# Database Home role, and Database role. Assumes that the Exadata Infrastructure has already been provisioned by Oracle.

- name: 'ExaCC Set-Up'
  hosts: 'localhost'
  
  tasks:

    - include_vars:
        file: './vars/{{ item }}'
      loop: '{{ vars_list }}'
    
    - name: 'Create VM Cluster Network and VM Cluster for ExaCC'
      include_role:
        name: 'exacc_vm_cluster'
    
    